#!/usr/bin/env ruby
#
# Copyright 2016, DAQRI LLC.
#
# This code is covered by the MIT License (see LICENSE.txt)

require 'landscape-turner/restore'

if ENV['USER'] != "root"
  puts "You must have root permissions to run this tool."
  exit
end

Restore.restore_with_cli_args
